# Installer for proflow `main.yml` into roles, or current tasks
---
- hosts: localhost
  gather_facts: no

  vars:
    # Indicates whenever `apply.yml` applies to single tasks folder (option `no`)
    # or multiple tasks folder for different roles (option `yes`)
    multiple: no
    # A list for remote role folders for applying `main.yml`
    # Empty list for applying to all role folders
    # Only used when `local == 'no'`
    target: []

  tasks:
    - include_vars:
        file: "galaxy.yml"
    
    - debug:
        msg: "ansible-proflow v{{ version }} 'apply' playbook for roles"

    - name: proflow | apply in local tasks
      set_fact:
        __to__:
          - "{{ playbook_dir }}"
      when: not multiple | bool

    - name: proflow | apply in specific role tasks
      set_fact:
        __to__: "{{ target | map('regex_replace', '^(.*)$', playbook_dir + '/roles/\\1') | list }}"
      when:
        - multiple | bool
        - target | length > 0

    - find:
        paths: "{{ playbook_dir }}/roles"
        file_type: directory
      register: __roles__
      when:
        - multiple | bool
        - target | length == 0

    - name: proflow | apply in all role tasks
      set_fact:
        __to__: "{{ __roles__ | json_query(\"files[].path\") }}"
      when:
        - multiple | bool
        - target | length == 0

    - debug:
        var: __to__

    - include_tasks:
        file: tasks/role.yml
      loop: "{{ __to__ }}"
      loop_control:
        loop_var: __role_dir__
