# Installer for proflow `main.yml` into roles, or current tasks
---
- hosts: localhost
  gather_facts: no

  vars:
    # Indicates whenever `apply.yml` applies to local tasks folder (option `yes`)
    # or multiple tasks folder for different roles (option `no`)
    local: yes
    # A list for remote role folders for applying `main.yml`
    # Empty list for applying to all role folders
    # Only used when `local == 'no'`
    target: []

  tasks:
    - include_vars:
        file: "galaxy.yml"
    
    - debug:
        msg: "ansible-proflow v{{ version }} 'apply' playbook for roles"

    - include_tasks:
        file: tasks/role.yml
      loop:
        - "{{ playbook_dir }}"
      loop_control:
        loop_var: __role_dir__
