# Installer for proflow `main.yml` into roles, or current tasks
---
- hosts: localhost
  gather_facts: no

  vars:
    # Indicates whenever `main.yml` applies to current working directory (option `yes`)
    # or multiple tasks folder for roles in current working directory (option `no`)
    current: yes

    # A list for remote role folders for applying `main.yml`
    # Empty list for applying to all role folders
    # Only used when `current == 'no'`
    target: []

  tasks:
    - include_vars: galaxy.yml
    
    - debug:
        msg: "Applying {{ name }} v{{ version }} | Please view playbook.yml for EXTRA_VARS info"

    - name: proflow | apply in current working directory
      set_fact:
        __to__:
          - "{{ playbook_dir }}"
      when: current | bool

    - name: proflow | apply in specific role tasks
      set_fact:
        __to__: "{{ target | map('regex_replace', '^(.*)$', playbook_dir + '/roles/\\1') | list }}"
      when:
        - not current | bool
        - target | length > 0

    - find:
        paths: "{{ playbook_dir }}/roles"
        file_type: directory
      register: __roles__
      when:
        - not current | bool
        - target | length == 0

    - name: proflow | apply in all role tasks
      set_fact:
        __to__: "{{ __roles__ | json_query(\"files[].path\") }}"
      when:
        - not current | bool
        - target | length == 0

    - include_tasks:
        file: tasks/role.yml
      loop: "{{ __to__ }}"
      loop_control:
        loop_var: __role_dir__
