name: build-deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make galaxy.yml
      run: make galaxy.yml

    - name: Build and Deploy Collection
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: '${{ secrets.GALAXY_API_KEY }}'
