name: lint
on:
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0
