name: lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: "./apply.yml"
